# .github/workflows/deploy-backend.yml
name: Deploy Backend to Cloud Run

on:
  push:
    branches: [main]
    paths:
      - "apps/backend/**"
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read
  id-token: write        # OIDC 토큰 발급

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 체크아웃
    - uses: actions/checkout@v4

    # 2. OIDC → Google Cloud 로그인
    - id: auth
      uses: google-github-actions/auth@v1   # 구글 공식 액션
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
        service_account:           ${{ secrets.SERVICE_ACCOUNT }}

    # 3. Buildx 준비
    - uses: docker/setup-buildx-action@v3   # BuildKit 기반 멀티 플랫폼

    # 4. Docker 이미지 빌드 & Artifact Registry 푸시
    - name: Build and push
      uses: docker/build-push-action@v5
      working-directory: apps/backend        # ← 컨텍스트 기준 디렉터리 :contentReference[oaicite:2]{index=2}
      with:
        context: .
        push: true
        provenance: false                    # 메타데이터 충돌 방지
        tags: >
          ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wyc-atoz-backend/backend:${{ github.sha }}

    # 5. Cloud Run 배포
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ secrets.RUN_SERVICE }}
        region:  ${{ secrets.GCP_REGION }}
        image:   ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wyc-atoz-backend/backend:${{ github.sha }}
        traffic-percentages: '100'
