# .github/workflows/deploy-backend.yml
name: Deploy Backend to Cloud Run

on:
  push:
    branches: [main]                # main 브랜치에만 배포
    paths:
      - "apps/backend/**"           # 백엔드 코드 변경 시
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read
  id-token: write                   # OIDC 토큰 발급용(필수)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 체크아웃
    - uses: actions/checkout@v4

    # 2. OIDC → Google Cloud 로그인
    - id: "auth"
      uses: google-github-actions/auth@v1              # 구글 공식 액션 :contentReference[oaicite:0]{index=0}
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
        service_account:           ${{ secrets.SERVICE_ACCOUNT }}

    # 3. Buildx 준비
    - uses: docker/setup-buildx-action@v3              # BuildKit 기반 멀티 플랫폼 :contentReference[oaicite:1]{index=1}

    # 4. Docker 이미지 빌드 & Artifact Registry 푸시
    - name: Build and push
      uses: docker/build-push-action@v5                # docker 공식 액션 :contentReference[oaicite:2]{index=2}
      with:
        context: ./apps/backend
        push: true
        provenance: false                              # 이미지 메타 충돌 방지 :contentReference[oaicite:3]{index=3}
        tags: >
          ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wyc-atoz-backend/backend:${{ github.sha }}

    # 5. Cloud Run 배포
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2   # deploy-cloudrun 액션 :contentReference[oaicite:4]{index=4}
      with:
        service: ${{ secrets.RUN_SERVICE }}
        region:  ${{ secrets.GCP_REGION }}
        image:   ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wyc-atoz-backend/backend:${{ github.sha }}
        traffic-percentages: '100'                     # 새 revision에 100% 전환
