# .github/workflows/deploy-backend.yml
name: Deploy Backend to Cloud Run

on:
  push:
    branches: [main]              # main 브랜치에 푸시되면 자동 배포
    paths:
      - "apps/backend/**"         # 백엔드 코드 변경
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read
  id-token: write                 # OIDC 토큰 발급(필수)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v4

      # 2) Google Cloud 로그인 (OIDC)
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
          service_account:           ${{ secrets.SERVICE_ACCOUNT }}
          token_format: "access_token"          # ← access_token 출력

      # 3) Artifact Registry 로그인 (Docker)
      - name: Docker login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # 4) Buildx 준비
      - uses: docker/setup-buildx-action@v3

      # 5) Docker 이미지 빌드 & 푸시
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/apps/backend
          push: true
          provenance: false              # Cloud Run과 충돌 방지
          tags: >
            ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wyc-atoz-backend/backend:${{ github.sha }}

      # 6) Cloud Run 배포
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.RUN_SERVICE }}
          region:  ${{ secrets.GCP_REGION }}
          image:   ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wyc-atoz-backend/backend:${{ github.sha }}
          traffic-percentages: '100'
