# .github/workflows/deploy-backend.yml
name: Deploy Backend to Cloud Run

on:
  push:
    branches: [main]
    paths:
      - "apps/backend/**"
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4     # ① 코드 체크아웃

      - id: auth                      # ② OIDC 로그인
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
          service_account:           ${{ secrets.SERVICE_ACCOUNT }}

      - uses: docker/setup-buildx-action@v3   # ③ Buildx 준비

      # ④ 이미지 빌드 & 푸시
      - name: Build and push
        working-directory: apps/backend        # ← 'uses:'와 같은 레벨
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wyc-atoz-backend/backend:${{ github.sha }}

      # ⑤ Cloud Run 배포
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.RUN_SERVICE }}
          region:  ${{ secrets.GCP_REGION }}
          image:   ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/wyc-atoz-backend/backend:${{ github.sha }}
          traffic-percentages: '100'
